
spring.application.name=VidhataSocietyMLMBackend
server.servlet.context-path=/mlm
server.port=8081
#Database info
spring.datasource.driver-class-name=oracle.jdbc.driver.OracleDriver
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/orcl
 
 
spring.datasource.username=system
spring.datasource.password=Oracle1234
 
#jpa properties
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.OracleDialect
